#!/bin/sh
set -x
git submodule init
git submodule update
{
cat <<EOT
gitconfig           .gitconfig
tmux.conf           .tmux.conf
vim                 .vim
vimrc               .vimrc
go_packages         .go_packages
zshrc               .zshrc
zsh                 .zsh
EOT
} | while read origin symlink ; do
    rm -rf ~/$symlink
    ln -f -s $PWD/$origin ~/$symlink
done

