alias ls='ls --color=auto -phG'
alias l='ls'
alias s='ls'
alias ks='ls'
alias ll='ls -l'
alias la='ls -a'
alias mntcoins='mkdir ~/coins; sshfs s1111355@`curl http://kudaranu.atumari.net/get_host.pl`:/home/ugrad/11/s1111355 ~/coins && cd ~/coins'
alias umntcoins='umount ~/coins && rm -rf ~/coins'
alias mntjitsui='mkdir ~/jitsui; sshfs web@sohosai.tsukuba.ac.jp:/var/www ~/jitsui -p 10101 && cd ~/jitsui'
alias umntjitsui='umount ~/jitsui && rmdir ~/jitsui'
alias isinstalled="sudo find `perl -e'print \"@INC\"'` -name '*.pm' -print 2>/dev/null|grep"
alias javac='javac -J-Dfile.encoding=UTF-8'
alias java='java -Dfile.encoding=UTF-8'
alias dgcc='gcc -D DEBUG_MODE'
#alias splint='splint -exitarg +matchanyintegral -warnposix -exportlocal -nullpass -nullret -mustfreefresh -retvalint -branchstate -nullassign -dependenttrans'
alias gcc='gcc -std=c99 -Wall -Wextra -pedantic -Wformat=2 -Wstrict-aliasing=2'
alias g++='g++ -std=c++11 -Wall -Wextra -pedantic -Wformat=2 -Wstrict-aliasing=2'
alias mysqlstart='sudo /opt/local/share/mysql5/mysql/mysql.server start'
alias mysqlstop='sudo /opt/local/share/mysql5/mysql/mysql.server stop'
alias ocaml='rlwrap ocaml'
alias out='afplay ~/.shellinfo/bin/OUT.mp3&'
alias ah='afplay ~/.shellinfo/bin/ah.mp3&'
alias m='afplay ~/.shellinfo/bin/m.mp3&'
alias wow='afplay ~/.shellinfo/bin/wow.mp3&'
alias runmode='RPROMPT=""; PROMPT="[eric@TSUBAKI]%% "'
alias gip='curl http://siritori.info/ip.php'

# JavaScript
alias lessc='~/node_modules/less/bin/lessc'
alias recess='~/node_modules/recess/bin/recess'
alias jshint='~/node_modules/jshint/bin/hint'
alias uglifyjs='~/node_modules/uglify-js/bin/uglifyjs'
alias gosh="rlwrap -b '(){}[],#\";|' gosh"
alias glgcc='gcc -L/usr/X11R6/lib/ -lglut -lGLU -lGL -lXmu -lX11'
alias glg++='g++-mp-4.6 -std=c++0x -L/usr/X11R6/lib/ -lglut -lGLU -lGL -lXmu -lX11'
alias history='history -f'

